apiVersion: v2
name: helm
description: A Helm chart for Kubernetes

type: application

version: "0.1.0"

# elCicdChart chart
dependencies:
- name: elCicdChart
  version: 0.1.0
  repository: https://raw.githubusercontent.com/elcicd/el-CICD-deploy/main/charts/
  # repository: file://../../el-CICD-deploy/charts/elCicdChart
- name: elCicdResources
  version: 0.1.0
  repository: https://raw.githubusercontent.com/elcicd/el-CICD-deploy/main/charts/
  # repository: file://../../el-CICD-deploy/charts/elCicdResources
  import-values:
  - data